mailchimp/mailchimp-client-lib-codegen

.github/workflows/create-release-marketing.yml, .github/workflows/create-release-transactional.yml
Previously, workflows only ran on pushes to master. This PR runs workflows on all pull requests, albeit without publishing internally or externally.
=> Run workflows on pull requests as well as pushes

swagger-config/marketing/javascript/templates/ApiClient.mustache, swagger-config/marketing/php/templates/api.mustache, swagger-config/marketing/python/templates/rest.mustache, swagger-config/marketing/ruby/templates/api_client.mustache, swagger-config/transactional/javascript/templates/ApiClient.mustache, swagger-config/transactional/php/templates/Configuration.mustache, swagger-config/transactional/python/templates/api_client.mustache, swagger-config/transactional/ruby/templates/api_client.mustache
Updates default request timeouts to match those of the corresponding API (120s for Marketing, 300s for Transactional).
=> MAIL-230: Set default timeout for client libs

.github/workflows/build-dev-site.yml, .github/workflows/create-release-marketing.yml, .github/workflows/create-release-transactional.yml
Adds a workflow for rebuilding the dev site, via Netlify build hooks.
Pushes to master should prompt a rebuild of prod and the dev site, while PR's should rebuild the staging branch, which is deployed to a separate Netlify build environment.
This action only initiates the build; currently there isn't any feedback regarding whether or not the build was successful (at least here). There may be ways to wire this up using Netlify deploy notifications, but currently we have notifications set up in Slack and elsewhere so I think that it's alright that that info isn't surfaced here in GitHub.
=> MAIL-424: Add dev site rebuild workflow

.github/workflows/build-dev-site.yml, .github/workflows/create-release-marketing.yml, .github/workflows/create-release-transactional.yml
Previously, each workflow file ran on PR / push to the file itself, which was redundant since Actions already enacts this. Having the path included led to the workflows running when they shouldn't, e.g. attempting to publish externally on a push [(link)](https://github.com/mailchimp/mailchimp-client-lib-codegen/actions/runs/267263069) that shouldn't have published a new version.
=> Remove self from workflow rebuilds

.github/workflows/create-release-marketing.yml, .github/workflows/create-release-transactional.yml
This PR preserves the git history of the client lib repos by cloning the `.git` directory before adding and pushing changes. Previously we were initting and force pushing on each deploy, such that the repos all only had 1 commit at any time.
=> MAIL-450: Preserve git history by cloning client repo before pushing

.gitignore, spec/README.md
The previous spec file was edited to make it possible to create SDKs. I backfilled most of the edits into the code that's used to serve the spec file in production. This PR contains that new spec file, as well as a README about how to manually keep it up-to-date.
Don’t bother diffing the spec files themselves because the formatting is different and everything gets weird (unless you want to download the files manually and pipe ’em through `json.tool` or what-have-you). Future updates to the spec file should be more readable though, since they’ll be coming from a consistent source.
=> Update marketing spec, and add README about how to do it

.github/workflows/create-release-marketing.yml, .github/workflows/create-release-transactional.yml
Clones full repo to allow for adding to the working tree. Previously, we were running `git clone --bare` which prevents adding to the working tree, causing the build step to fail.
=> Fix git pipeline error in internal deploy action

README.md, swagger-config/marketing/javascript/templates/README.mustache, swagger-config/marketing/php/templates/README.mustache, swagger-config/marketing/python/templates/README.mustache, swagger-config/marketing/ruby/templates/README.mustache, swagger-config/transactional/javascript/templates/README.mustache, swagger-config/transactional/php/templates/README.mustache, swagger-config/transactional/python/templates/README.mustache, swagger-config/transactional/ruby/templates/README.mustache
Adds the following banner image to all client library READMEs, to match this repo and the dev site.
=> Add MCDEV banner image to all client lib READMEs

spec/transactional.json
Update the send_at description to remove an unnecessary/inaccurate sentence.
=> Remove unnecessary sentence from send_at for messages/send

spec/transactional.json, swagger-config/transactional/php/templates/composer.mustache
Update Guzzle to version 7.2. See this PR for more information https://github.com/mailchimp/mailchimp-transactional-php/pull/4
Note that this means the SDK will require PHP7.
=> Update guzzle to recent version for transactional SDKs

spec/transactional.json, swagger-config/transactional/javascript/templates/package.mustache
More here: https://github.com/axios/axios/pull/3410.
Fixes https://github.com/mailchimp/mailchimp-transactional-node/pull/2.
=> [transactional-node] Bump axios to ^0.21.1 to patch security vulnerability

.github/workflows/create-release-marketing.yml
Composer was running PHP 8, which was causing problems with dependencies. Pin to 7.4.
=> Pin PHP version to 7.4 for marketing sdk tests

swagger-config/marketing/ruby/templates/api_client.mustache
API Keys in basic auth headers need to be base-64 encoded. This is from a PR that @cheldasan opened against the Ruby SDK.
None, but will be sure to diff the SDKs before merging.
=> Merge PR to use base64 encoding for API key in Ruby SDK

swagger-config/marketing/php/templates/README.mustache, swagger-config/transactional/php/templates/README.mustache
We require PHP 7.2 in our composer files; also added a note about this to our README for marketing & transactional.
=> Update PHP README to indicate 7.2 is required

swagger-config/marketing/php/templates/api.mustache, tests/marketing-php/MarketingTest.php
It seems like `csv` type `collectionFormat` parameters do not get encoded correctly:
https://github.com/swagger-api/swagger-codegen/issues/10046
The generated code seems accept the array as the query parameter if given, instead of respecting the `collectionFormat`.  The current behavior seems to encode the parameters into the `multi` format by default, due to `Guzzle`s handling of arrays.
```php
>>> $field_parameters = ["fields" => ["id", "name"]];
=> [
"fields" => [
"id",
"name",
],
]
>>> $query = \GuzzleHttp\Psr7\build_query($field_parameters);
=> "fields=id&fields=name"
```
This is technically an invalid query parameter for our `fields` parameter, since we ask for a `csv` type, or `fields=id,name`.
After this change:
```php
php > …
```
=> Handle collection serialization of query parameters

swagger-config/transactional/python/templates/api_client.mustache
@rtr3 noted a warning because we were using `is` to compare strings instead of `==`. Fixed this in the template file.
=> Use '==' instead of 'is' for string comparison in python transactional library

spec/transactional.json
Publishing the SDKs from PR https://github.com/mailchimp/mailchimp-client-lib-codegen/pull/152 failed because I forgot to bump the version number; bump it now.
=> Bump version (forgot in previous PR)

swagger-config/marketing/ruby/templates/README.mustache
Adds enums to our campaign statuses, landing page statuses, and fixes documentation around the `activity-feed` endpoint.
https://github.com/mailchimp/mailchimp-marketing-ruby/pull/10
=> [APIC-755] Update documentation, fix readme

.github/workflows/create-release-marketing.yml, .github/workflows/create-release-transactional.yml, spec/transactional.json
My previous PR was a bit greedy with the find & replace - our codegen libraries are still using `master` as the default branch, and I was trying to push to a `main` brach on them, which does not exist.
This PR should fix this for the `marketing` and `transactional` repos.
=> [APIC-757] Fix workflows to push to master branch of codegen repos

.github/workflows/build-dev-site.yml
Currently the Dev build hook is unused, because we only have prod (`mc-developer-prod.netlify.app`) and staging (`mc-developer.netlify.app`).
=> Remove Dev build hook (since only prod / staging currently exist)

spec/transactional.json, swagger-config/marketing/ruby/templates/api_client.mustache, swagger-config/marketing/ruby/templates/gemspec.mustache, swagger-config/transactional/ruby/templates/gemspec.mustache
Making fixes from two PRs
This one https://github.com/mailchimp/mailchimp-marketing-ruby/pull/9
Because I was doing some local builds of the gem. Doesn't look like the `test_files` configuration is used by us.
And https://github.com/mailchimp/mailchimp-marketing-ruby/pull/6
Which fixes the fact that query parameters were left out as options for POST/PATCH/PUT/DELETE even though the API does support some query params on those methods.
I rebuilt the ruby gem locally and used it to POST list members with the skip_merge_validation query parameter. Seems like everything should work and be backwards compatible with current callers, but Ruby is not my strong suit.
=> Ruby - allow posting query parameters

.github/workflows/create-release-marketing.yml, .github/workflows/test-marketing.yml, .github/workflows/validate-and-generate-marketing.yml
A few changes to our github actions:
1.  📦 Create Marketing Release => only runs when pushing to main
2. Two new actions are created:
* `Test Marketing Client Libraries` => uses `workflow_run`, allowing secrets, to run the build through our test suite.
* `Validate and Generate Marketing Client Libraries` => validates the code, generates the libraries, and adds them to the cache
The new validation actions is activated only on pull requests, or if a `test-marketing` label is added.  The testing action only runs when the validation completes, and because it uses `workflow_run`, it allows secrets.
**Note** - I'm using a few actions from the Github Actions marketplace, so there may be security implications to consider here.
Non-internal actions i'm using: …
=> New github actions to allow testing on forks

.github/workflows/test-marketing.yml
We will attempt to test the repo, even if we haven't added the label (thus, the validation step was skipped).
I didn't account for the fact that cla-bot adds a label as well, and thought that `workflow_run` would only run when the previous step succeeded.  That is not the case.
=> Fix github action

.github/workflows/build-dev-site.yml, .github/workflows/test-marketing.yml, .github/workflows/test-transactional.yml
This changes our Build Developer Site action to only run on merges to main, and adds the staging build to both our transactional and marketing workflow run actions.
=> Rebuild Staging Docs in Workflow Run Action

spec/transactional.json
We recently added the ability to verify domains via TXT record. A new parameter in the API response, verify_txt_key has been added to the /senders/check-domain, /senders/add-domain, and /senders/domains endpoints. The key contains a unique string that can be appended to 'mandrill_verify.' and added the domains' TXT records to verify.
=> verify_txt_key parameter added to 3 /senders/ endpoints

CHANGELOG.md, spec/transactional.json, swagger-config/transactional/php/templates/Configuration.mustache
Per https://github.com/mailchimp/mailchimp-client-lib-codegen/pull/245
Opening a separate PR for this change.  This is slightly awkward for existing users who may be expecting a string from the error states, however, the contract is currently a string _or_ a concrete exception, so I'm hoping that this isn't too rough.
There is also an existing PR on the repository asking for this change.
https://github.com/mailchimp/mailchimp-transactional-php/pull/5
=> Return the exception directly in mailchimp-transactional-php

CHANGELOG.md, generate-sdks, spec/transactional.json
I made a mistake in #249 - the `output_dir` changes for the `php` client libraries, and thus, my Changelog wasn't being persisted to those artifacts.
=> Fix changlog placement for custom output directory

CHANGELOG.md, spec/transactional.json
This adds the new /allowlists/ series of endpoints to the Transactional API reference, as well as a new /exports/allowlist endpoint. The old endpoints will not be depreciated until much further down the road, but these new endpoints are now live and should be used instead.
=> Allowlists Endpoints

CHANGELOG.md, spec/transactional.json
Updated the "reject_reasons" response for /messages/send and /messages/send-template to correctly use "hard-bounce" and "soft-bounce" instead of the previously stated "hard_bounce" and "soft_bounce".
=> updated reject_reasons

CHANGELOG.md, spec/transactional.json, swagger-config/transactional/javascript/templates/ApiClient.mustache
Allow users of the node transactional SDK to set the timeout for axios calls.
=> Add ability to override the default axios timeout

CHANGELOG.md
Simple documentation change for the `PATCH automations/.../emails/.../` endpoint on the marketing side.
=> [APIC] Update Patch Automations Emails Documentation

CHANGELOG.md, spec/transactional.json
The send_at description has been updated to reflect that users can only schedule the message within one year of the API call.
=> changed send_at descriptions, updated changelog

CHANGELOG.md, spec/transactional.json
This contribution fixes the incorrect template name usage in favor of the template slug which is the correct way.
=> Update messages/send-template to remove the template name reference

CHANGELOG.md, spec/transactional.json
Some `/template` endpoints include `is_broken_template` in the response, indicating if the template is malformed or corrupt. Adding that response to the documentation.
=> adding 'is_broken_template' response to some endpoints

.github/workflows/create-release-transactional.yml, CHANGELOG.md, spec/transactional.json, swagger-config/transactional/php/templates/Configuration.mustache
This fixes the ruby test that was broken and preventing new builds of the SDKs. It also updates the PHP SDK to use JSON in the requests instead of form_params.
=> fixing ruby test and php SDK json form

CHANGELOG.md, spec/transactional.json
The /senders/domains and /senders/check-domain endpoint now show information for `dkim2` and `dmarc` in the response. This PR adds the new response data to the API reference.
=> Dmarc update

.github/workflows/create-release-transactional.yml
Github workflow cannot use the default GitHub_token to push changes to different repository (than the one where workflow is initiated). Hence, we need to create a fresh PAT and make it available in workflow as secret
=> use another token for push to sdk repo

.github/workflows/create-release-transactional.yml
Adding ruby version 2.6.10 so that publish_ruby job succeeds
Using the latest actions/cache@v4 to get rid of the warnings in github workflow
=> specific ruby version and latest actions/cache

package.json
Since the Axios upgrade to v1 we need to use the commonjs version when running tests
=> Use commonjs axios build for tests

spec/transactional.json
maxLength only applies to strings
=> Fix array length

swagger-config/transactional/javascript/templates/ApiClient.mustache
Currently the ApiClient overrides the global axios timeout to 300s which is not expected, instead - create an axios instance and use it.
While migrating from `mandrill-api` npm package, we found that the mailchimp transactional is overriding axios global defaults, which is not expected. I would like to configure only mailchimp API actions timeout.
=> ApiClient: don't override global axios timeout

swagger-config/marketing/php/templates/Configuration.mustache
Generates the code for Marketing API that is breaking support for PHP 8.
PHP 8 does not allow the property creation on-the-fly
See https://php.watch/versions/8.2/dynamic-properties-deprecated for why this is necessary.
=> Generate code for marketing-php APIs variables

swagger-config/transactional/javascript/templates/package.mustache
Addresses [this vulnerability](https://security.snyk.io/vuln/SNYK-JS-AXIOS-7361793).
I did not manually test this package version change, but I reviewed the release notes for breaking changes compared to 1.7.0, and it's only a patch version bump.
=> Bump axios version in javascript transactional client to 1.7.7

swagger-config/marketing/php/templates/Configuration.mustache
Similar to #348, but for the marketing API
See https://php.watch/versions/8.2/dynamic-properties-deprecated for why this is necessary.
=> add public properties for php 8.2 support

swagger-config/marketing/ruby/templates/api_error.mustache
This PR is based on [a PR I originally opened on the generated mailchimp-marketing-ruby gem](https://github.com/mailchimp/mailchimp-marketing-ruby/pull/5) in 2021. At the time I didn't know that the gem was generated and the PR was rejected several months later. I never got around to submitting the patch to this project and have been using my own fork. However, I would like to see if my change could make it into this repo.
This PR should generally be backwards compatible, with the exception that the error _message_ won't show a stringified version of a ruby hash.
**Here's the summary from the original PR on the wrong repo:**
The `MailchimpMarketing::ApiError` is used to wrap up error responses from the Mailchimp API. This class is used to raise errors encountered by the `ApiClient` class. …
=> Parse ruby error response body and add attributes

swagger-config/marketing/javascript/templates/package.mustache, swagger-config/transactional/javascript/templates/package.mustache
`package.json` should include [SPDX license id](https://spdx.org/licenses/) in `license` field.
Hence: `Apache 2.0` → `Apache-2.0`.
=> Use SPDX license id in package.json

.github/workflows/test-marketing.yml
Update Ruby to use ruby/setup-ruby instead of the deprecated actions/setup-ruby
=> Update Ruby to use ruby/setup-ruby
