mailchimp/mailchimp-client-lib-codegen

swagger-config/marketing/ruby/templates/api.mustache
swagger-config/marketing/ruby/templates/api_client.mustache
swagger-config/marketing/ruby/templates/gemspec.mustache

This PR replaces the http client Faraday with Excon in the Ruby client.

[refactor]: replace Faraday w/ Excon

---

LICENSE

Fix year in LICENSE, d'oh

---

swagger-config/marketing/ruby/templates/api.mustache
swagger-config/marketing/ruby/templates/api_client.mustache

Update `marketing-ruby` responses to throw proper errors.

[refactor]: update marketing-ruby responses

---

generate-sdks
spec/transactional.json

This PR adds a script to `generate-sdks` to copy the LICENSE file over to the individual repos when generating.

add script to copy license to client libraries

---

.github/workflows/create-release-transactional.yml
spec/transactional.json
swagger-config/transactional/ruby/templates/api.mustache
swagger-config/transactional/ruby/templates/api_client.mustache
swagger-config/transactional/ruby/templates/gem.mustache
swagger-config/transactional/ruby/templates/gemspec.mustache

This PR updates the transactional-ruby templates to utilize the `excon` http client.

[refactor]: update transactional-ruby templates

---

.github/workflows/create-release-marketing.yml
.github/workflows/create-release-transactional.yml
spec/transactional.json

This PR adds the automated tests for each client wrappers as a step in the existing Github Actions workflow. In order for a new release to be created & published (internally or externally), all tests must pass.

MAIL-410: Add automated tests to Github Actions workflow

---

spec/transactional.json
swagger-config/marketing/php/templates/composer.mustache
swagger-config/transactional/php/templates/composer.mustache

This PR updates the minimum-stability level in composer.json to `dev`

MAIL-141: Updating minimum stability in composer.json

---

swagger-config/marketing/javascript/config.json
swagger-config/marketing/ruby/config.json
swagger-config/transactional/javascript/config.json
swagger-config/transactional/ruby/config.json

Updates client library package descriptions to reflect official status. This configuration is only available for Node and Ruby (not PHP or Python), so it only affects those SDKs.

MAIL-428: Update description for Node and Ruby client libraries to reflect official status

---

generate-sdks
spec/transactional.json
swagger-config/marketing/php/templates/ApiClient.php
swagger-config/marketing/php/templates/Configuration.mustache
swagger-config/marketing/php/templates/api.mustache
swagger-config/marketing/php/templates/composer.mustache
swagger-config/transactional/php/templates/ApiClient.php
swagger-config/transactional/php/templates/Configuration.mustache
swagger-config/transactional/php/templates/api.mustache
swagger-config/transactional/php/templates/composer.mustache

This PR addresses an issue in `mailchimp-marketing-php` & `mailchimp-transactional-php` w/ autoloading the ApiClient class.

fix: php composer setup

---

.github/workflows/create-release-marketing.yml
.github/workflows/create-release-transactional.yml
spec/transactional.json
swagger-config/marketing/php/templates/composer.mustache
swagger-config/transactional/php/templates/composer.mustache

This PR fixes an issue where the php client wrappers were not previously being tagged as stable releases.

fix: use stable version when pushing php wrappers

---

.github/workflows/create-release-marketing.yml
.github/workflows/create-release-transactional.yml
spec/transactional.json

This PR updates tagging in the Github Actions workflow on both php client wrappers.

fix: updating github actions tagging

---

.github/workflows/create-release-marketing.yml
.github/workflows/create-release-transactional.yml
spec/transactional.json

This PR adds a message flag when tagging via Github actions.

fix: add message flag to tag

---

.github/workflows/create-release-marketing.yml
.github/workflows/create-release-transactional.yml

Push tags to create updated release on marketing-php & transactional-php clients.

fix:update publish-php workflow

---

.github/workflows/create-release-marketing.yml
.github/workflows/create-release-transactional.yml

Adds adds marketing & transactional workflow updates as Github Actions triggers.

update: Add workflow files as actions triggers

---

swagger-config/marketing/php/templates/composer.mustache

This is just a newer version of ebrann94's PR, so I can test creating SDKs etc without rebasing.
The marketing SDKs will require PHP7 after this PR is merged.

Update guzzle to recent version (making new PR to re-test SDKs)

---

spec/transactional.json

Bump spec versions to trigger publish

Bump spec for Marketing and Transactional

---

spec/transactional.json

Forgot to bump the versions in the spec files, so the merge failed. Bumping now to propagate the README changes.

Bump version (even though it's a no-op)

---

.github/workflows/build-dev-site.yml
.github/workflows/create-release-marketing.yml
.github/workflows/create-release-transactional.yml
resources/swagger-original-templates/csharp/git_push.sh.mustache
resources/swagger-original-templates/java/git_push.sh.mustache
resources/swagger-original-templates/javascript/es6/git_push.sh.mustache
resources/swagger-original-templates/javascript/git_push.sh.mustache
resources/swagger-original-templates/php/git_push.sh.mustache
resources/swagger-original-templates/python/git_push.sh.mustache
resources/swagger-original-templates/ruby/git_push.sh.mustache
swagger-config/marketing/javascript/templates/README.mustache
swagger-config/marketing/php/templates/README.mustache
swagger-config/marketing/python/templates/README.mustache
swagger-config/marketing/python/templates/git_push.sh.mustache
swagger-config/marketing/ruby/templates/README.mustache
swagger-config/transactional/javascript/templates/README.mustache
swagger-config/transactional/php/templates/README.mustache
swagger-config/transactional/python/templates/README.mustache
swagger-config/transactional/ruby/templates/README.mustache

Prepping main to become the new deployment branch 
**Note** - a few things need to be done before this will work as we expect, including changes on the development site generator, and github actions here.

[APIC-757] Master => main in templates

---

.gitignore
spec/transactional.json
swagger-config/marketing/ruby/templates/gemspec.mustache
swagger-config/transactional/ruby/templates/gemspec.mustache

Small PR fixing our Ruby Gem homepage, as noted in this PR https://github.com/mailchimp/mailchimp-marketing-ruby/pull/8
Also adding .idea/ to our .gitignore for convenience
Tested the generated output, and it looked good to me.

Fixing the homepage and author for our rubygem

---

swagger-config/marketing/php/templates/composer.mustache

Looking to resolve the GuzzleHttp\Psr7\build_query compatability issue with the release of 2.0
Resolves #193

Resolve guzzle/psr7 versioning issue

---

spec/transactional.json
swagger-config/marketing/javascript/templates/package.mustache
swagger-config/marketing/ruby/templates/gemspec.mustache
swagger-config/transactional/ruby/templates/gemspec.mustache

These version change requests for security and compatibility look safe on review to me
Resolves #191 
Resolves #192

Updating various dependencies with security fixes

---

swagger-config/marketing/php/templates/api.mustache
swagger-config/marketing/php/templates/composer.mustache

This is a copy of https://github.com/mailchimp/mailchimp-client-lib-codegen/pull/197
We are still working on building out Github Actions which will allow us to run our test suites against forked repositories.  
Since this is already causing some pain, we decided to go ahead and merge this particular change directly.
#197

Guzzle psr7 upgrade

---

.github/workflows/create-release-transactional.yml
.github/workflows/test-transactional.yml
.github/workflows/validate-and-generate-transactional.yml

Basically a duplicate of https://github.com/mailchimp/mailchimp-client-lib-codegen/pull/209, but for the set of transactional actions.

Allow transactional fork and push testing

---

.github/ISSUE_TEMPLATE/MARKETING-ISSUE-FORM.yml
.github/ISSUE_TEMPLATE/TRANSACTIONAL-ISSUE-FORM.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/ref_issue.md

I didn't find a way to preview, but I'll revert if this doesn't look right.

Trying new issue forms

---

generate-sdks
sdk_pull_request_template.md
spec/transactional.json

Suggesting a PR template for the auto-generated repos

Add PR templates to the SDKs so its clear they're not supported

---

spec/transactional.json
swagger-config/marketing/javascript/templates/package.mustache
swagger-config/transactional/javascript/templates/package.mustache

Addresses #243 - pointed to this repositories issues for the `bugs` section, and added an `engines` field for node version 10 and above. 
#243

Update package.json template for node client

---

CHANGELOG.md
generate-sdks
spec/transactional.json

Adds a single changelog file, which will be updated to declare the changes each version has made.
Currently, this is a manual process, but we could always extend this to be programmatic.

Add a changelog to be pushed to all the codegen'd libraries

---

CHANGELOG.md

This adds a new endpoint, /3.0/account-exports/, to the marketing api clients.

Add the account exports marketing API

---

CHANGELOG.md
spec/transactional.json
swagger-config/transactional/php/templates/Configuration.mustache

Add method to set timeout in the Transactional PHP SDK.

Allow setting timeout for tx php sdk

---

spec/transactional.json

bumps spec for #280 - already shipped the marketing side.

Bump transactional spec

---

spec/transactional.json

redeploy python lib

---

.github/workflows/create-release-transactional.yml
.github/workflows/test-transactional.yml
CHANGELOG.md
spec/transactional.json

Builds were failing due to auth errors. The Github actions bot needed an updated user.email.

github actions bot

---

spec/transactional.json
swagger-config/transactional/php/templates/Configuration.mustache
swagger-config/transactional/php/templates/api.mustache

Changes to make PHP SDK compatible with PHP8.2

make php sdk php8.2 compatible

---

spec/transactional.json
swagger-config/transactional/javascript/config.json
swagger-config/transactional/javascript/templates/package.mustache

This PR bumps the Axios dependency which contains known vulnerability issues.
Following semver we have also proposed a new version as well
An issue discovered in Axios 0.8.1 through 1.5.1 inadvertently reveals the confidential XSRF-TOKEN stored in cookies by including it in the HTTP header X-XSRF-TOKEN for every request made to any host allowing attackers to view sensitive information.

Bumping transactional Axios dependency

---

.github/workflows/validate-and-generate-transactional.yml

Trigger validation and tests in every commit and consecutive commit

---

swagger-config/transactional/javascript/templates/ApiClient.mustache
swagger-config/transactional/javascript/templates/package.mustache

This PR sets the custom `User-Agent` for requests made using this library.
Also, it upgrades the underlying `axios` dependency
N/A

Setting custom User-Agent for requests

---

.github/workflows/test-marketing.yml
.github/workflows/test-transactional.yml

Fixing underlying Ruby dependencies when running tests

Bumping underlying Ruby version to 2.7

---

.github/workflows/create-release-marketing.yml
.github/workflows/create-release-transactional.yml
.github/workflows/test-marketing.yml
.github/workflows/test-transactional.yml
.github/workflows/validate-and-generate-marketing.yml
.github/workflows/validate-and-generate-transactional.yml
swagger-config/marketing/php/templates/Configuration.mustache

Here's a history of events:
1. 2024/02/13: I made a pull request #356
2. 2024/07/23: @webkod3r made and published #363 which was essentially a duplicate
3. 2024/12/11: @webkod3r published #356, now defining all the fields twice.
Also, the CI needs some love, https://github.com/mailchimp/mailchimp-client-lib-codegen/actions shows a ton of errors.
This PR fixes the duplicate fields, and a few CI issues, but there are probably more.

Fix dual attributes & some CI

---

.github/workflows/create-release-marketing.yml

Updates the `actions/cache` to v4.

Increment actions/cache to v4

---

.github/workflows/create-release-marketing.yml

Bumping the versions of Ruby and Python for our github actions. Tested this locally and everything was successfully generated.

Update Ruby and Python versions to build SDKs

---

.github/workflows/test-marketing.yml

Disable caching for Ruby

---

.github/workflows/create-release-marketing.yml
.github/workflows/test-marketing.yml

Update all workflows to use Ruby 2.7

---

spec/transactional.json

Fix a typo in the transactional spec, and ensure the build process still works as expected.

Fix a typo
